server:
  port: 8282
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    job:
      enabled: false
  output:
    ansi:
      enabled: ALWAYS

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
